### ISSUE TITLE
chrome folder already exists

### ISSUE THREAD

**Issue by Groschenroman** [niutech/comic-sans-replacer#1]
Hi there,

first of all, thanks for this terrific optimization of Comic Sans. And for the replacer, of course!
Since I'm still learning how to use these kind of snippets and plugins I'm not quite sure what to do on this issue:
In my profile directory there is already a folder named "chrome". It contains two files: "userChrome-example.css" and "userContent-example.css".
Do I have to replace this folder, rename it as a backup or just paste the userContent.css in there?

Thanks for helping out – and your work!

**Comment by niutech** [comment]
Just paste the CSS file there and restart the browser.

**Comment by Groschenroman** [comment]
Thx for the quick answer. It works!
