### ISSUE TITLE
Languages ​​with diacritics

### ISSUE THREAD

**Issue by vndmtrx** [niutech/comic-sans-replacer#2]
I was using the font for a job and found out that it lacks the characters for letters that have accentuation, such as "á" "ê" "ì" and "ã", in lowercase as well as in uppercase version.

**Comment by niutech** [comment]
The font creator Craig Rozynski said they will be added "sonner rather
than later" (https://twitter.com/craigrozynski/status/460350678204817409).

**Comment by vndmtrx** [comment]
Thx
