### ISSUE TITLE
Firefox replacing problem

### ISSUE THREAD

**Issue by OMGchangeMYusername** [niutech/comic-sans-replacer#3]
i know it's just because of me,but please can you detail the Firefox replacer a little more?
i hope you can help :D

**Comment by niutech** [comment]
Comic Sans Replacer is a special userContent.css stylesheet, which overrides some CSS styles on every web page. For more details on how replacing works in Firefox, go to the [MozillaZine KB](http://kb.mozillazine.org/UserContent.css).
