### ISSUE TITLE
Provide a release

### ISSUE THREAD

**Issue by Supuhstar** [niutech/comic-sans-replacer#4]
Normal users aren't going to want to follow complex instructions for installation. They're going to want to download an installer, run the installer, and get it over with. Even better if this is just on the Chrome/Firefox/IE/Opera extension store.

**Comment by OMGchangeMYusername** [comment]
Wurst is auto updating whenever there is a new release,there is no need for installer and such.
I don't understand what's so complex about placing a folder in `C:\Users\NotYourBusiness\AppData\Roaming\.minecraft\versions` anyway...

**Comment by niutech** [comment]
It is on the [Chrome Web Store](https://chrome.google.com/webstore/detail/hogcjpgnoecbkmbamlakaacafkloopbn). Installer is an overkill just for a single CSS file.
